### PR TITLE
Add projects to in-the-wild page.

### PR DESCRIPTION
**Pull request by smeghead**
Add some projects to in-the-wild page.

* [phel-lifegame](https://github.com/smeghead/phel-lifegame) The Lifegame using the CLI terminal written in phel.
* [phel-saraudon](https://github.com/smeghead/phel-saraudon) A command to Visualize result of `git log --stat`.
* [phel-cellular-automaton](https://github.com/smeghead/phel-cellular-automaton) The cellular automaton using the CLI terminal written in phel.

### CODE REVIEW

**Comment by smeghead** [comment]
@Chemaclass 
phel-str and phel-pdo have already been transferred under phel-lang.
Should phel-str, phel-pdo be removed from the in-the-wild page?

**Comment by Chemaclass** [comment]
@smeghead good idea. Instead of removing them you can point them to the phel-lang org, so it's a way to help people finding projects within the ecosystem.
Btw, very nice projects what you're working on!

**Comment by smeghead** [comment]
@Chemaclass 
phel-str has been removed as it has been moved to phel-lang itself.
Added phel-schema in addition to phel-pdo.

**Review by Chemaclass — APPROVED** [review]
Thank you!

**Pull request merged**
