### PR TITLE
Add Releases blog section

### PR DESCRIPTION
**Pull request by Chemaclass**
## 🔖  Changes

- Create a new blog section named "Releases"
  - Add the CHANGELOG from releases for each mayor-minor version (not hotfixes) to individual blog posts.

This is a concept I wanted to try and experiment with. What do you think, @jenshaase & @JesusValera?

Screenshot 2022-01-28 at 23 59 48

Screenshot 2022-01-29 at 00 01 51

### CODE REVIEW

**Review by JesusValera — COMMENTED** [review]
I am not sure 100% if I like it, but if we do, definitely I would add a lateral menu as we have in "Docs" menu, right now it's a bit complicated to go to some specific version.

I did a mockup with the idea. What do you think?

image

**Comment by Chemaclass** [comment]
As we already talked, there is no real benefit on simply duplicating the Changelog in GitHub and in the website. Instead, we should create some documented blog posts with code examples. Do we want to keep anything from this PR, or should we close it, @jenshaase?

**Comment by jenshaase** [comment]
I think we should convert this to a Blog section. Not sure if we should keep anything of this or start a new PR.

**Comment by Chemaclass** [comment]
Then I will just close it, no worries. As I said it was a partially a draft :)

**Pull request closed without merging**
