### PR TITLE
Fix sidebar column

### PR DESCRIPTION
**Pull request by Chemaclass**
## 🔖 Changes

- Fix the sidebar column to the left side. It is scrollable for smaller screens.
- Anchor links displayed after the header, and not hidden under it.

### CODE REVIEW

**Review by JesusValera — COMMENTED** [review]
I like the idea, but if the screen is small, can you scrolling?

**Comment by Chemaclass** [comment]
@JesusValera yes, It's scrollable. I updated the PR description with that info.

**Review by JesusValera — APPROVED** [review]

**Comment by mabasic** [comment]
I am not a big fan of the right sidebar for TOC. I think that it ruins the UX and I have found that other languages/platforms are avoiding it too. Three columns is too much, but the rest of the changes look awesome.

**Comment by JesusValera** [comment]
> I am not a big fan of the right sidebar for TOC. I think that it ruins the UX and I have found that other languages/platforms are avoiding it too. Three columns is too much, but the rest of the changes look awesome.

I am fine with the three columns, also, it is visible only for extra big screens, but maybe you are right. What do you think @Chemaclass @jenshaase ? :)

**Comment by jenshaase** [comment]
I took a look and saw a few error.

## Desktop
screen-1

1. There is a strange padding at the left bottom of the navigation. Also the gray line is not going further. What is the reason for that?
2. Same on the right side. 
3. The gray lines is stopping in the middle of nowhere.
4. I get a scroll indicator and can scroll the left navigation, although I see every item of the navigation.
5. There are too many gray lines for my taste now. You have gray lines to separate the navigation from the content and gray lines to separate code from text.

## Mobile
screen-2

The bullet points are missing. If you wanted to remove them there is still some unnecessary padding left

## General

* I see a reason for keeping the left navigation fixed, but I'm not sure if I want to maintain this CSS. I probably built to many websites with fixed elements and know that these arise more problems then they solve.
* I think the TOC on the top is enough. The sections are currently not so long that you get lost in the side.

**Comment by Chemaclass** [comment]
Thanks a lot for the feedback @mabasic, @jenshaase and @JesusValera! I already fixed all the desktop and mobile errors that @jenshaase found. Please, give it another try and let me know if it's better now. (PS: I updated the PR Description with the new design). 

Regarding the TOC fixed on the right side: my idea was to put it only for big screen (when >1400px), otherwise it will stay on top. I found this in some documentation websites and found it myself really interesting and useful to have. Here you can see pretty similar examples:
- https://docs.spryker.com/docs/scos/dev/developer-getting-started-guide.html
- https://docs.github.com/en/get-started/quickstart/hello-world

The only "bad thing" I can see is, as @jenshaase already mentioned, that we need to maintain this "complex" css (fixed columns are more complex than non-fixed, that's true), but I think it gives us a nice UX when entering the website. I would vote for keep it and if we face any problem maintaining this part (the fixed TOC, for example) we can easily remove it in the future. I can be responsible for this, not a big problem :)

**Comment by mabasic** [comment]
Wanted to contribute with a thing that happened not long ago.

I started learning F# and got stuck on the documentation page for Fable (and other packages). They had three columns layout with TOC being on the right and they had a huge number of issues with it (the scroll did not work, the markup was complex, there were weird mobile issues etc...) After asking people what they thought they all agreed that three column layout was not good, so they switched to a two column layout.

https://github.com/MangelMaxime/Nacara

I have helped the author with small contributions regarding the design and layout.

In the end we ended with two column layout with TOC being integrated in the left sidebar which (TOC) is only visible when you are on that section in the documentation.

I have found that other languages like [rescript](https://rescript-lang.org/docs/manual/latest/overview) have done this too and it feels intuitive to use and does not take extra space.

Considering that making something like that is complex especially if you want the sidebar to be sticky when you scroll down, I would be happy with having the TOC above the content and having the sidebar to the left. This way your eyes need to go left-right. When you have a three column layout with TOC being on the right you end up with your eyes going like this left-right-right-left.

I'm not against the three column layout, but I find it to be inferior to other solutions

**Comment by Chemaclass** [comment]
To reduce friction in this PR, I will remove the TOC column in this PR and leave only the fix of the sidebar. And I will create a follow up PR with the fixing of the TOC on the right column for big screens.

**Comment by Chemaclass** [comment]
Closed in favor of https://github.com/phel-lang/phel-lang.org/pull/23

**Pull request closed without merging**
